### ISSUE TITLE
Handle absent patches in reports

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#110]
At present, invocations of skt without patches applied produce the following
in reports:

    We applied the following patch:

    on top of commit 23b389c23139 from the repository at
       git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git 

Fix the reports to produce appropriate text for these cases.

**Comment by veruu** [comment]
I didn't even notice this, thanks for filing the issue!
