### ISSUE TITLE
Use proper data format / CSV parser

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#119]
At the moment, we replace all commas with semicolons in patch names (subjects) so that they do not clash with commas in CSV files we write later. Stop doing that by e.g. using a proper CSV writer (from the `csv` module), or better yet by switching to a structured file format which would also get rid of the structure depending on the order of class member calls.

**Comment by veruu** [comment]
Using a proper CSV or other method sounds like a more foolproof idea. Parsing of info currently fails with multiline values even if they are totally valid in some cases.

**Comment by veruu** [comment]
support for infourl which contained these data was removed so this is no longer relevant
