### ISSUE TITLE
Explicitely say why the rest of the series is left out with patch application failures

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#136]
The report for patch application failures lists applied patches and says `However, the application of the last patch above failed with the following output: <ERROR>`. This turned out to be confusing since there is no mention of the rest of the series. They obviously weren't applied because it makes no sense to try to apply subsequent patches after application error, but we should mention it in the report.

Perhaps something like `Pleas note that if there are subsequent patches in the series, they weren't applied because of the error message stated above.` at the end of the report?

Suggestions for other friendly messages welcome. cc @major @dzickusrh

**Comment by dzickusrh** [comment]
That works for me, just add an 'e' to 'Pleas', please. :-)

**Comment by veruu** [comment]
I thought we long ago agreed on a fact that I can't write :)

**Comment by dzickusrh** [comment]
I will file an issue tracker to fix that. ;-)
