### ISSUE TITLE
Fix usage of kerneltree.get_commit_hash() in artifacts names

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#242]
If the base reference is specified (most of the time it is, since we want to use a baseline that works), `kerneltree.get_commit_hash()` will always return it. This is totally fine and expected for most of the uses of the function, but its result should not be used to distinguish build artifact names -- if more builds on top of the same baseline are supposed to be published at the same spot, they overwrite each other which leads to very unexpected results.

`buildhead` in `cmd_merge()` should not be using this function, but instead getting the hash of the last patch that was just applied, and later uses of `buildhead` should use not only `buildhead`, but build architecture or something similar (and possibly timestamp too) to properly distinguish between builds; to not break if the same series are being tested on multiple architectures and the publishing directory is the same one for more of them.

**Comment by spbnick** [comment]
We need this fixed, as the workaround with random temporary directory names doesn't work when skt tries to refer to the baseline build to check if baseline still works. We need to refer to builds by their final commit hash.

**Comment by spbnick** [comment]
We only have jobs passing now, because the baseline build is still in the old location.

**Comment by spbnick** [comment]
Or perhaps we can simply disable baseline builds. We need to check the logs and see if those actually run. If not, we can avoid fixing this now. Ideally, I would prefer skt not to assume the storage structure and locations are uniform across runs as it does now.
