### ISSUE TITLE
Remove `lastsubmitted` from `skt.runner.BeakerRunner`

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#281]
The `lastsubmitted` field in `skt.runner.BeakerRunner` seems to have been added for convenience of not needing to pass `jobid`. However, this kind of logic is mostly useful for human interfaces, in an internal interface it just complicates things and creates confusion. Remove `lastsubmitted` and require always specifying `jobid`.

**Comment by danghai** [comment]
Is there a typo in title in issue? It should be `skt.runner.BeakerRunner` instead of `sktm.runner.BeakerRunner`

**Comment by spbnick** [comment]
Yep, thanks, fixed!
