### ISSUE TITLE
Support ordered mixture of merge arguments

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#284]
Right now, `--merge-ref`, `--patch` and `--pw` options can be all supplied at once, but they are always applied in the order specified above, which is not very useful. While we are going to make the options mutually exclusive for now, it might be worth a discussion if it would make sense to implement the ability to specify different options at once and apply them in the order they were specified in.

**Comment by danghai** [comment]
@veruu I swap the order these options. Ex `--pw` , `--merge-ref`, `--patch`, and it still works. Or do I misunderstand the issue?

**Comment by veruu** [comment]
Yes. The merge command should keep the *order* the options were added from the command line in. If you check the output of the command, it's always the same order and not the one specified by the user

**Comment by danghai** [comment]
Ah I see, you want to keep them `order`. However, the flexible order also has benefit For example: the users do not need to exactly remember its order.

**Comment by veruu** [comment]
I think we are talking about two different things :)

Currently, if you run merge with options `--pw <url> --patch <path> --merge-ref '<url> <ref>'`, first the `--merge-ref` will be applied, then `--patch` and then `--pw`. This is different order from what the user specified on the command line. If the user wants to first apply a patch from Patchwork and only then one from their computer, they should be able to do it, but we don't allow it now.

**Comment by danghai** [comment]
I know what you mean by comparing `order` option of input with `order` option of output. But you said `we don't allow it now`, so it should keep the `order` option to make sure `order` of input and output is the same. However, what about making flexible order option of output is the same as flexible option of input?

**Comment by danghai** [comment]
@veruu Sorry I make you confused. So which the output do you want when you run merge with option `--pw <url> --patch <path> --merge-ref '<url> <ref>'`, It will pop up the error and tell the user should run merge following correct order `-merge-ref  --patch <path> --pw <url> ` ?

**Comment by veruu** [comment]
No, we want to apply the options in the order the user specified them. The order in which you apply patches does matter, so saying "do it in a different order" doesn't work and will fail.
