### ISSUE TITLE
Use constants for success/fail/error instead of 0/1/2

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#287]
As @danghai pointed out in one of the pulls, it would be more clear to understand than plain numbers.

Implement some simple constants like `SKT_SUCCESS = 0`, `SKT_FAIL = 1`, `SKT_ERROR = 2`, and then use these across the code instead of the direct numeric values where required.

**Comment by danghai** [comment]
I see I need to change for both file `executable` and `runner`. Do you want me create the `misc.py` being the same as `sktm`?

**Comment by veruu** [comment]
Also the return values in `merge_git_ref` method and possibly elsewhere. Yes, the `misc` file sounds good, we could then move the functions from init file there later as well.

**Comment by danghai** [comment]
I prefer cutting the `SKT` prefix because it is long. I already create the PR and ready for review.

**Comment by veruu** [comment]
@danghai I think that in the long run, specific names would be better. For example someone will implement another runner and retrieve success and failure info from there. Differentiating between `SUCCESS` and `success` isn't obvious. In this case, the `SKT_` prefix would mark that it's a repo-wide value.

**Comment by danghai** [comment]
@veruu It makes sense. I will fix it. what about `kernelbuilder`? It only has one place to replace.
https://github.com/RH-FMK/skt/blob/master/skt/kernelbuilder.py#L228

**Comment by veruu** [comment]
That's a return code from make, and it should be compared with the standard numeric values and not our arbitrary ones. If there was an assignment or return based on it, that's the one that should be changed

**Comment by danghai** [comment]
Ah right. It is from `subprocess`
