### ISSUE TITLE
Enhance result string for merge 

### ISSUE THREAD

**Issue by danghai** [RH-FMK/skt#312]
Because we are going to implement the ordered mixture of merge arguments following multiple patch, the `result string` only stores `True`/`False`. In my opinion, `result string` should be enhanced by providing more detail information. Ex:
```
<Name of Patch1> : True
<Name of Patch2> : True
<Name of Patch3> : False
``` 
What do you think?

**Comment by veruu** [comment]
The `result_string` is meant to be an indicator of the command result - something like permanent storage of return code. There is a huge discussion in [meta/6](https://github.com/RH-FMK/meta/pull/6) if you want to follow the reasoning, but the short version is

- if the command didn't complete (eg. got an unexpected exception), there is no file with the result
- if the command completed unsuccessfully, there is a result file with `false` string
- if the command completed successfully, there is a result file with `true` string

The strings are shell commands at the same time, so the files are easy to process by machine. What patches were applied should be present in the report itself (`report_string` and file that's created if the command completes).
