### ISSUE TITLE
Reporter.py: MailReporter has no '_getjobids' member

### ISSUE THREAD

**Issue by danghai** [RH-FMK/skt#346]
@veruu I see you remove `_getjobids` in this commit:
https://github.com/RH-FMK/skt/pull/331/commits/d86b20740cd31335267fe87f2f49946a87e919ff
But it still is used `_getjobids` here:
https://github.com/RH-FMK/skt/blob/master/skt/reporter.py#L603

**Comment by veruu** [comment]
Good catch! We mostly use the multireport so we didn't catch this (how did it pass testing?). The line should have read the jobs from `self.cfg` instead

**Comment by danghai** [comment]
@veruu I am not sure about the `test` that you imply. So I need to keep the `_getjobids` method to handle this bug?

**Comment by veruu** [comment]
No. The value should be read from `self.cfg` instead of calling nonexistent method

**Comment by danghai** [comment]
@veruu you mean `self.cfg.get("jobs")`?
