### ISSUE TITLE
Use keyword arguments when initializing skt.kbuilder

### ISSUE THREAD

**Issue by major** [RH-FMK/skt#42]
The arguments list for `skt.kbuilder` is getting a bit long with the addition of `enable_debuginfo`. We should change this to use named arguments instead.

This was noted by @spbnick in #33.

**Comment by veruu** [comment]
There is [PEP-3102](https://www.python.org/dev/peps/pep-3102/) for enforcing keyword arguments in Python3 (and mentions how to implement it in Python2 where it isn't supported). Or do you only have in mind changing optional argument passing from
```builder = skt.kbuilder(workdir, base, cfg, makeopts, debug)``` to ```builder = skt.kbuilder(workdir, base, cfgtype=cfg, makeopts=makeopts, enable_debuginfo=debug)``` ?

**Comment by spbnick** [comment]
@veruu, I guess I just want to see which argument means what and the second way you specify helps :)
