### ISSUE TITLE
skt merge creates relative workdir under workdir

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#51]
After executing the following command right outside the workdir (`skt-workdir`):

    skt --rc skt-rc --state --workdir skt-workdir -vv \
        merge --baserepo git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git \
              --ref a870a02cc963de35452bbed932560ed69725c4f2 \
              --pw https://patchwork.ozlabs.org/patch/886637

The workdir has `skt-workdir` directory created under it.

**Comment by danghai** [comment]
This bug still takes place when you re-run the command: 

```
$ skt --rc skt-rc --state --workdir skt-workdir -vv \
         merge --baserepo git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git \
               --ref master
```

**Comment by veruu** [comment]
I'm not encountering this problem anymore, fixed by today's patches around `wdir` expansion. Closing, please reopen in case it shows up again.
