### ISSUE TITLE
skt running in a virtualenv cannot run bkr

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#62]
When skt is installed with pip inside a virtualenv, its execution of `bkr` command fails with something like this:

    Traceback (most recent call last):
      File "/home/worker/runner/workspace/skt_test@tmp/virtualenv/bin/bkr", line 7, in <module>
        from bkr.client.main import main
      File "/home/worker/runner/workspace/skt_test@tmp/virtualenv/lib/python2.7/site-packages/bkr/client/main.py", line 16, in <module>
        import krbV

**Comment by spbnick** [comment]
@major, could you please figure out a fix for this?

**Comment by spbnick** [comment]
Or should I use `--system-site-packages` here?

**Comment by major** [comment]
Sure. I'll work on that now.

**Comment by major** [comment]
@spbnick I added this to: https://github.com/RH-FMK/skt/pull/59/commits/4618fb4d3923c239e4c905e5ecbe67afaeec8711 in #59 since I made the beaker-client installation optional there.

In your gate jobs, be sure to install `skt` with `[beaker]` on the end. For example:

    pip install git+https://github.com/RH-FMK/skt[beaker]
