### ISSUE TITLE
skt always uses XMLRPC to retrieve patches to apply during merge

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#98]
see `ktree.merge_patchwork_patch` . This can be an issue especially with Patchwork2 instances that have the legacy interface turned off. We need to fix the patch retrieval, either using direct mbox URLs or a wrapper that would check which interface (REST/XMLRPC) is available and use that.

**Comment by spbnick** [comment]
Could we perhaps forgo the notion of Patchwork in skt altogether? Let it simply accept URLs to local files or to patches on Patchwork? And make sktm deal with posting checks (and mailing results)?

**Comment by veruu** [comment]
By simply using the provided URLs with `/mbox` appended, we shouldn't need to deal with any differences between Patchwork versions. I don't think we use Patchwork interfaces elsewhere in skt (please correct me if I'm wrong) so that's basically what I'm proposing

**Comment by spbnick** [comment]
Right, I missed the mbox part. Gotta wrap up for today, I guess :weary: :smiley:.
