### ISSUE TITLE
merge_patch_file doesn't provide logs if the patch application fails

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#99]
While the `ktree.merge_patchwork_patch` provides logs about the patch application failure, the sister method `ktree.merge_patch_file` does not. This means we don't have any feedback to report to the patch author if the patch failed to apply.

Because of the similarity between the functions that would be introduced by the fix, it would be nice if we could make the `merge_patchwork_patch` retrieve the patch file and then use `merge_patch_file` internally.

**Comment by danghai** [comment]
@veruu. I am not sure about `patchlist`, and look for an example `patchlist`. For `patchwork`: 
`--pw <PATCHWORK_PATCH_URL>`. For example: `--pw https://patchwork.ozlabs.org/patch/886637`. What about `patchlist`? Is it good if we provide `patchlist` option in `README` for clear?

**Comment by veruu** [comment]
@danghai sure, go ahead!
